# Generated by Django 4.2.6 on 2023-10-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.PositiveIntegerField(choices=[(3, 'ADMIN'), (2, 'MAYDON EGALARI'), (1, 'USER')], default=1),
        ),
    ]
