# Generated by Django 4.2.6 on 2023-10-10 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stadiummodel',
            old_name='address',
            new_name='address',
        ),
    ]
